server:
  addr: 0.0.0.0:2830
  timeout: 2s
  domain: http://ğŸ®ğŸº.cf/
data:
  database:
    driver: mysql
    source: tinyurl:tinyurl@tcp(127.0.0.1:3306)/tinyurl?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
log:
  level: info
  output: std #file
  development: true
  rotate:
    filename: ./app.log
    maxsize: 10  #Mb
    maxage: 7 #day
    # maxbackups: 
    # localtime: 
    # compress: 
